services:
  mygogs:
    image: gogs/gogs:0.13
    volumes:
      - ./gogs-data:/data
    networks:
      bw-services:
        aliases:
          - mygogs
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://mygogs:3000
      - bunkerweb.REVERSE_PROXY_HEADERS_1=Authorization $http_authorization
      - bunkerweb.MAX_CLIENT_SIZE=1G
      - |
        bunkerweb.CUSTOM_CONF_MODSEC_CRS_gogs=SecAction "id:900220,phase:1,nolog,pass,t:none,setvar:'tx.allowed_request_content_type=|application/x-www-form-urlencoded| |multipart/form-data| |multipart/related| |text/xml| |application/xml| |application/soap+xml| |application/x-amf| |application/json| |application/cloudevents+json| |application/cloudevents-batch+json| |application/octet-stream| |application/csp-report| |application/xss-auditor-report| |text/plain| |application/x-git-upload-pack-request| |application/x-git-receive-pack-request|'"

networks:
  bw-services:
    external: true
    name: bw-services
