services:
  bunkerweb:
    image: bunkerity/bunkerweb:${TAG}
    labels:
      bunkerweb.INSTANCE: "yes"
    environment:
      SERVER_NAME: ""
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      USE_BUNKERNET: "no"
      USE_BLACKLIST: "no"
      USE_WHITELIST: "no"
      SEND_ANONYMOUS_REPORT: "no"
    networks:
      bw-universe:
        aliases:
          - bunkerweb

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:${TAG}
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: ""
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      DATABASE_URI: "${DATABASE_URI}"
      USE_BUNKERNET: "no"
      USE_BLACKLIST: "no"
      USE_WHITELIST: "no"
      SEND_ANONYMOUS_REPORT: "no"
      DOCKER_HOST: "tcp://bw-docker:2375"
    volumes:
      - bw-data:/data
      - bw-db:/usr/share/bunkerweb/db
      - bw-sqlite:/var/lib/bunkerweb
    networks:
      bw-universe:
        aliases:
          - bw-scheduler
      bw-db:
        aliases:
          - bw-scheduler
      bw-docker:
        aliases:
          - bw-scheduler

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    networks:
      bw-docker:
        aliases:
          - bw-docker

volumes:
  bw-data:
    name: bw-data
  bw-db:
    name: bw-db
  bw-sqlite:
    name: bw-sqlite

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-db:
    name: bw-db
  bw-docker:
    name: bw-docker
