services:
  mongo:
    image: mongo:7
    networks:
      bw-services:
        aliases:
          - mongo
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # replace with a less obvious username
      - MONGO_INITDB_ROOT_PASSWORD=toor # replace with a better password
      - MONGO_INITDB_DATABASE=mongo # replace with the database name of your choice

  mongo-ui:
    image: mongo-express:1-20-alpine3.19
    networks:
      bw-services:
        aliases:
          - mongo-ui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root # replace with a less obvious username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor # replace with a better password
      - ME_CONFIG_BASICAUTH_USERNAME=changeme # replace with a better username
      - ME_CONFIG_BASICAUTH_PASSWORD=changeme # replace with a better password
    restart: unless-stopped
    depends_on:
      - mongo
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://mongo-ui:8081
      - |
        bunkerweb.CUSTOM_CONF_MODSEC_mongo-express=
        SecRule REQUEST_FILENAME "@rx ^/db" "id:1,ctl:ruleRemoveByTag=attack-generic,ctl:ruleRemoveByTag=attack-protocol,nolog"

volumes:
  db-data:

networks:
  bw-services:
    external: true
    name: bw-services
