services:
  mytomcat:
    image: tomcat:11.0
    volumes:
      - ./app:/usr/local/tomcat/webapps/ # folder containing war files
    networks:
      bw-services:
        aliases:
          - mytomcat
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://mytomcat:8080

networks:
  bw-services:
    external: true
    name: bw-services
