services:
  mytomcat:
    image: tomcat:11.0
    configs:
      - source: tomcat_app_war
        target: /usr/local/tomcat/webapps/sample.war
        uid: "0"
        gid: "0"
        mode: 0444
    networks:
      - bw-services
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL=/
        - bunkerweb.REVERSE_PROXY_HOST=http://mytomcat:8080

networks:
  bw-services:
    external: true
    name: bw-services

configs:
  tomcat_app_war:
    file: ./app/sample.war
