services:
  app1:
    image: nginxdemos/nginx-hello
    networks:
      bw-services:
        aliases:
          - app1
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL_1=~ ^/app1/(.*)$$
      - bunkerweb.REVERSE_PROXY_HOST_1=http://app1:8080/$$1
      - |
        bunkerweb.CUSTOM_CONF_SERVER_HTTP_redirects=
        port_in_redirect off;
        location ~ ^/(app1|app2)$$ {
          rewrite ^(.*)$$ $$1/ permanent;
        }

  app2:
    image: nginxdemos/nginx-hello
    networks:
      bw-services:
        aliases:
          - app2
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL_2=~ ^/app2/(.*)$$
      - bunkerweb.REVERSE_PROXY_HOST_2=http://app2:8080/$$1
      - |
        bunkerweb.CUSTOM_CONF_SERVER_HTTP_redirects=
        port_in_redirect off;
        location ~ ^/(app1|app2)$$ {
          rewrite ^(.*)$$ $$1/ permanent;
        }

networks:
  bw-services:
    external: true
    name: bw-services
