services:
  myredmine:
    image: redmine:6-alpine
    restart: "unless-stopped"
    volumes:
      - redmine-data:/usr/src/redmine/files
    networks:
      - bw-services
    environment:
      - REDMINE_DB_POSTGRES=mydb
      - REDMINE_DB_DATABASE=redminedb
      - REDMINE_DB_USERNAME=user
      - REDMINE_DB_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL=/
        - bunkerweb.REVERSE_PROXY_HOST=http://myredmine:3000

  mydb:
    image: postgres:17-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "db-user-pwd" # replace with a stronger password (must match REDMINE_DB_PASSWORD)
      POSTGRES_DB: "redminedb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - bw-services
    deploy:
      placement:
        constraints:
          - "node.role==worker"

networks:
  bw-services:
    external: true
    name: bw-services

volumes:
  redmine-data:
  db-data:
