services:
  # you will need to add a user by hand
  # example : docker-compose exec mypassbolt su -m -c "/usr/share/php/passbolt/bin/cake passbolt register_user -u <your@email.com> -f <yourname> -l <surname> -r admin" -s /bin/sh www-data
  # more info at https://github.com/passbolt/passbolt_docker
  mypassbolt:
    image: passbolt/passbolt:latest-ce
    networks:
      - bw-services
    environment:
      - APP_FULL_BASE_URL=https://www.example.com # replace with your URL
      - DATASOURCES_DEFAULT_HOST=mydb
      - DATASOURCES_DEFAULT_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
      - DATASOURCES_DEFAULT_USERNAME=user
      - DATASOURCES_DEFAULT_DATABASE=passbolt
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "mydb:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.ALLOWED_METHODS=GET|POST|HEAD|PUT|DELETE
        - bunkerweb.COOKIE_FLAGS=* SameSite=Lax
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL=/
        - bunkerweb.REVERSE_PROXY_HOST=https://mypassbolt
        - |
          bunkerweb.CUSTOM_CONF_MODSEC_CRS_passbolt=
          SecRule REQUEST_FILENAME "@rx ^/locales" "id:1000000,ctl:ruleRemoveById=953100,nolog"

  mydb:
    image: mariadb:11
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bw-services
    environment:
      - MYSQL_ROOT_PASSWORD=db-root-pwd # replace with a stronger password
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=user
      - MYSQL_PASSWORD=db-user-pwd # replace with a stronger password (must match DATASOURCES_DEFAULT_PASSWORD)
    deploy:
      placement:
        constraints:
          - "node.role==worker"

networks:
  bw-services:
    external: true
    name: bw-services

volumes:
  db-data:
  gpg_volume:
  jwt_volume:
