services:
  myjoomla:
    image: joomla:5-apache
    networks:
      bw-services:
        aliases:
          - myjoomla
    volumes:
      - joomla-data:/var/www/html
    environment:
      - JOOMLA_DB_HOST=mydb
      - JOOMLA_DB_NAME=joomla_db
      - JOOMLA_DB_USER=user
      - JOOMLA_DB_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://myjoomla
      - bunkerweb.LIMIT_REQ_URL_1=/administrator/
      - bunkerweb.LIMIT_REQ_RATE_1=8r/s
      - bunkerweb.LIMIT_REQ_URL_2=/installation/index.php
      - bunkerweb.LIMIT_REQ_RATE_2=8r/s

  mydb:
    image: mariadb:11
    volumes:
      - db-data:/var/lib/mysql
    networks:
      bw-services:
        aliases:
          - mydb
    environment:
      - MYSQL_ROOT_PASSWORD=db-root-pwd # replace with a stronger password
      - MYSQL_DATABASE=joomla_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=db-user-pwd # replace with a stronger password (must match JOOMLA_DB_PASSWORD)

volumes:
  joomla-data:
  db-data:

networks:
  bw-services:
    external: true
    name: bw-services
